export enum AMPLITUDE_EVENT {
  PAGE_VIST = "PAGE_VISIT",
  WALLET_SEARCH = "WALLET_SEARCH",
  REQUEST_ERROR = "REQUEST_ERROR",
  IMAGE_LOAD_ERROR = "IMAGE_LOAD_ERROR",
  LOCAL_STORAGE_UPDATE = "LOCAL_STORAGE_UPDATE",
  API_RESPONSE_TIME = "API_RESPONSE_TIME",
  DISABLED_INTEGRATION_CHANGE = "DISABLED_INTEGRATION_CHANGE",
}
